#!/usr/bin/env python3
"""
setup_and_deploy.py
-------------------
MTA Enterprise Workforce System — One-Click Setup Script

This script:
  1. Creates the .env file with your Supabase connection string
  2. Runs the SQL schema in your Supabase database
  3. Runs the full ETL pipeline to load all data
  4. Deploys the API + dashboard to Vercel

Usage:
  python3 setup_and_deploy.py
"""

import os
import sys
import subprocess
import socket

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
VENV_PYTHON = os.path.join(BASE_DIR, ".venv", "bin", "python3")


def print_header(text):
    print("\n" + "═" * 60)
    print(f"  {text}")
    print("═" * 60)


def print_step(n, total, text):
    print(f"\n[{n}/{total}] {text}")


def run(cmd, cwd=None, env=None):
    """Run a shell command and stream output."""
    result = subprocess.run(cmd, shell=True, cwd=cwd or BASE_DIR, env=env)
    return result.returncode


# ── STEP 1: Get Supabase credentials ─────────────────────────
print_header("MTA Enterprise — Setup & Deploy")
print("\nYou'll need your Supabase database password.")
print("(The password you set when creating the project)")
print()

db_password = input("  Enter your Supabase database password: ").strip()
if not db_password:
    print("  ✗ Password cannot be empty. Exiting.")
    sys.exit(1)

project_ref = "ycwoygmintlafapwtmpx"

# Build both connection strings
direct_url       = f"postgresql://postgres:{db_password}@db.{project_ref}.supabase.co:5432/postgres"
transaction_url  = f"postgresql://postgres.{project_ref}:{db_password}@aws-0-us-east-1.pooler.supabase.com:6543/postgres"

print(f"\n  ✓ Connection strings built for project: {project_ref}")

# ── STEP 2: Write .env ────────────────────────────────────────
print_step(1, 4, "Writing .env file...")

env_content = f"""# MTA Enterprise Workforce System — Environment Variables
# Auto-generated by setup_and_deploy.py

# PostgreSQL — Direct Connection (local ETL use)
DATABASE_URL={direct_url}

# PostgreSQL — Transaction Pooler (Vercel serverless use)
DATABASE_URL_TRANSACTION={transaction_url}

# API Settings
API_HOST=0.0.0.0
API_PORT=8000
ENVIRONMENT=production

# CORS (allow all for now)
CORS_ORIGINS=*

# BigQuery (optional — leave blank to skip)
BIGQUERY_PROJECT_ID=
BIGQUERY_DATASET_ID=mta_workforce_analytics
"""

env_path = os.path.join(BASE_DIR, ".env")
with open(env_path, "w") as f:
    f.write(env_content)
print(f"  ✓ .env written → {env_path}")

# Reload env for this process
from dotenv import load_dotenv
load_dotenv(env_path, override=True)

# ── STEP 3: Run SQL schema ────────────────────────────────────
print_step(2, 4, "Running SQL schema in Supabase...")

schema_path = os.path.join(BASE_DIR, "database", "schema.sql")
psql_cmd = f'psql "{direct_url}" -f "{schema_path}" 2>&1'

print(f"  Connecting to: db.{project_ref}.supabase.co:5432")
rc = run(psql_cmd)

if rc != 0:
    print("  ⚠ psql not found or connection failed. Trying via Python/SQLAlchemy...")
    try:
        from sqlalchemy import create_engine, text
        engine = create_engine(direct_url, connect_args={"connect_timeout": 10})
        with open(schema_path) as f:
            schema_sql = f.read()
        with engine.connect() as conn:
            # Execute each statement separately
            for stmt in schema_sql.split(";"):
                stmt = stmt.strip()
                if stmt and not stmt.startswith("--"):
                    try:
                        conn.execute(text(stmt))
                    except Exception as e:
                        if "already exists" in str(e).lower():
                            pass  # Tables already exist — safe to continue
                        else:
                            print(f"    Warning: {e}")
            conn.commit()
        print("  ✓ Schema created successfully via SQLAlchemy!")
    except Exception as e:
        print(f"\n  ✗ Database connection failed: {e}")
        print("\n  → Check your password is correct")
        print(f"  → Connection: {direct_url[:60]}...")
        sys.exit(1)
else:
    print("  ✓ Schema created successfully via psql!")

# ── STEP 4: Run ETL pipeline ──────────────────────────────────
print_step(3, 4, "Running full ETL pipeline (loading data into Supabase)...")
print("  This will load 1,000 employees + 4,828 time log records...")

rc = run(f"{VENV_PYTHON} -m pipeline.main")
if rc != 0:
    print("  ✗ ETL pipeline failed! Check logs/etl.log for details.")
    sys.exit(1)

print("  ✓ ETL pipeline complete — data loaded!")

# ── STEP 5: Vercel deploy ─────────────────────────────────────
print_step(4, 4, "Deploying to Vercel...")
print()
print("  You'll be guided through Vercel login and deployment.")
print("  When asked:")
print("    - Link to existing project? → N (No)")
print("    - What's the project name? → mta-enterprise-system")
print("    - In which directory? → ./ (just press Enter)")
print()
input("  Press Enter to start Vercel deployment...")

# Deploy
rc = run("vercel --yes 2>&1")

if rc == 0:
    print("\n  ✓ Deployed to Vercel successfully!")
    print()
    print("  Now set the DATABASE_URL environment variable in Vercel:")
    print(f"    vercel env add DATABASE_URL")
    print(f"    → When prompted, paste: {transaction_url}")
    print()
    print("  Then redeploy to apply the env var:")
    print("    vercel --prod")
else:
    print("\n  ⚠ Vercel deployment had issues. Run manually:")
    print("    vercel login")
    print("    vercel deploy")

print_header("SETUP COMPLETE!")
print()
print("  Your MTA Enterprise System is deployed.")
print(f"  Supabase DB: db.{project_ref}.supabase.co")
print()
print("  Quick test your API locally:")
print("    source .venv/bin/activate")
print("    uvicorn api.main:app --reload")
print("    → Open: http://localhost:8000/docs")
print()
